chore(typing): help `mypy` match `@overload`
`pyright` doesn't need this, `mypy` infers this as `str` - which is too wide

> narwhals/_arrow/namespace.py:372: error: No overload variant of "binary_join_element_wise" matches argument types "Generator[ChunkedArray[StringScalar], None, None]", "str"  [call-overload]> narwhals/_arrow/namespace.py:372: note: Possible overload variants: