refactor: Cache, reuse `Implementation._backend_version` (#2764)
* docs: Remove outdated doc

I shoul've caught that in review (https://github.com/narwhals-dev/narwhals/pull/2620#discussion_r2143068085)

* perf: Cache `Implementation._backend_version`

Mentioned in
- https://github.com/narwhals-dev/narwhals/pull/2620#discussion_r2140114096
- https://github.com/narwhals-dev/narwhals/discussions/1657#discussioncomment-12211098

Now that validation happens **within** that call, we can remove it from every `Series`, `DataFrame`, `LazyFrame` constructor and stop passing it around

* perf: Remove `validate_backend_version`

* test: Update `test_to_native_namespace_min_version`

* refactor: Port over `EagerDataFrame`

`lazy()` and `collect()` between backends is really the only place we might need to preserve the current checks

* refactor: Port over `EagerSeries`

* refactor: Port `Eager(Expr|Then)`, `(Arrow|Pandas)Selector`

* refactor: Port `EagerNamespace`

* refactor: Port `EagerSeriesNamespace`

* refactor: No more `backend_version` eager utils!

* docs: Fix `how_it_works.md`

We don't need the version anymore

https://github.com/narwhals-dev/narwhals/actions/runs/15982913249/job/45081217959?pr=2764

* revert: Remove unused `EagerSeries._validate_backend_version`

https://github.com/narwhals-dev/narwhals/actions/runs/15982913252/job/45081168507

* ci: fix pandas cov

https://github.com/narwhals-dev/narwhals/actions/runs/15982913252/job/45081168507

* fix cov pattern

https://github.com/narwhals-dev/narwhals/actions/runs/15983209178/job/45082089100?pr=2764

* refactor: Port `LazyExpr` + friends

* refactor: Port `PolarsExpr`, `CompliantExpr`

* refactor: Port `PolarsSeries`, `_polars.utils`

* refactor: Port `_dask.utils`

Now `mypy` understands the same error as `pyright` 😏

* refactor: Port `CompliantNamespace` + friends

* refactor: Port `Compliant(Data|Lazy)Frame` + friends

* refactor: Move `_validate_backend_version` into a protocol

* chore: `polars` cov

* feat: Support `ibis` in `.lazy()`?

- Seemed the easiest way to get coverage
- Will split into another PR
- https://ibis-project.org/reference/expression-tables#ibis.memtable

* test: `from_arrow` coverage

* ignore spark cov

* chore: `get_dask` coverage

* fix imports and `import_check`

Was broken on windows
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 21406: character maps to <undefined>

* revert: just ignore `dask` cov

- https://github.com/narwhals-dev/narwhals/actions/runs/16004869123/job/45148957046
- https://github.com/narwhals-dev/narwhals/pull/2764/commits/2de591058a76977552fae1910567858398c30534

* refactor: Cleaning up

* refactor: Replace more `parse_version`