refactor: remove `Array` shape default
We get the `TypeError` for free:
```py
import narwhals as nw
>>> nw.Array(nw.Int64)
TypeError: Array.__init__() missing 1 required positional argument: 'shape'
```