chore: Spec `CompliantLazyFrame` (#2232)
* chore(typing): Mostly finish `CompliantLazyFrame`

* fix: add missing `CompliantDataFrame.explode`

* feat(typing): Adds `not_implemented.deprecated`

Only way I've come up with to preserve the deprecation message

* chore(typing): Finish `PolarsLazyFrame`

* chore(typing): Finish `SparkLikeLazyFrame`

* chore(typing): Finish `DaskLazyFrame`

* chore(typing): Finish `DuckDBLazyFrame`

* fix(typing): `PandasLikeDataFrame.explode`

* chore(typing): Mark `.lazy` return as `Incomplete`

I can't work out what is the desired behavior

* chore(typing): Fill `Incomplete` for `*Expr`

* revert: remove `.to_(arrow|pandas)`

https://github.com/narwhals-dev/narwhals/pull/2232#issuecomment-2733466145

* fix(DRAFT): Expose `CompliantLazyFrame.native`

- Will need something similar with `DataFrame`
- Aiming to solve https://github.com/narwhals-dev/narwhals/issues/2239#issuecomment-2733748367

* fix: remove default in `CompliantLazyFrame.lazy`

```py
narwhals/_compliant/dataframe.py:262: error: Definition of "lazy" in base class "CompliantDataFrame" is incompatible with definition in base class "CompliantLazyFrame"  [misc]
    class EagerDataFrame(
    ^
```

* fix(typing): Align `unique` sigantures

3x of these:
```py
error: Signature of "unique" incompatible with supertype "CompliantLazyFrame"  [override]
```

Even though `maintain_order` is unused - `EagerDataFrame` (and subclasses) require the same signature

* fix: coverage for `PolarsLazyFrame.native`

https://github.com/narwhals-dev/narwhals/actions/runs/13929256423/job/38981936344

* fix(typing): Add missing `_change_version` method

> error: Cannot access attribute "_change_version" for class "CompliantLazyFrame[Any, FrameT@_stableify]"

* chore(typing): Mark intended annotation, that isn't valid yet

`mypy` expands to an invalid type
> "CompliantLazyFrame[Any, NativeFrame]" of "Any | CompliantLazyFrame[Any, NativeFrame] | CompliantLazyFrame[Any, DataFrame[Any]] | CompliantLazyFrame[Any, LazyFrame[Any]] | CompliantLazyFrame[Any, DataFrameLike]"

* revert: remove `CompliantLazyFrame.lazy`

https://github.com/narwhals-dev/narwhals/pull/2232#discussion_r2001879563

* lol `maintain_order` default one side only 😅

Resolves https://github.com/narwhals-dev/narwhals/pull/2232#discussion_r2003019826

* revert: don't widen `keep` for lazy

* make `keep` a keyword again

conflict from (#2247)