fix(typing): Align `unique` sigantures
3x of these:
```py
error: Signature of "unique" incompatible with supertype "CompliantLazyFrame"  [override]
```

Even though `maintain_order` is unused - `EagerDataFrame` (and subclasses) require the same signature