fix(typing): Add missing `_change_version` method
> error: Cannot access attribute "_change_version" for class "CompliantLazyFrame[Any, FrameT@_stableify]"